name: continuous-integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    container:
      image: michaelfbryan/mdbook-docker-image
    steps:
    - uses: actions/checkout@v3
    - run: mdbook build
    - uses: actions/upload-artifact@v3
      with:
        name: book
        path: ./book

  upload-book:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build-book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: book
          path: ./book
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
