name: continuous-integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    container:
      image: michaelfbryan/mdbook-docker-image
    steps:
    - uses: actions/checkout@v4
    - run: mdbook build
    - uses: actions/upload-artifact@v4
      with:
        name: book
        path: ./book

  upload-book:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build-book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: book
          path: ./book
      - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
